export default {
  'ui.pressStart': 'PRESS START',
  'ui.tapToStart': 'TAP TO START',
  'ui.getReady': 'GET READY',
  'ui.stage': 'STAGE',
  'ui.missionComplete': 'MISSION COMPLETE',
  'ui.continue': 'CONTINUE?',
  'ui.gameOver': 'GAME OVER',
  'ui.eo': 'EMERGENCY ORDER',
  'ui.eoClear': 'ORDER CLEARED',
  'ui.eoFail': 'ORDER FAILED',
  'ui.climaxReady': 'CLIMAX READY',
  'ui.shotDown': 'SHOT DOWN',
  'ui.lock': 'LOCK',
  // radio: [callsign, line]
  'r.s1.launch': ['BOSS', 'Hawk, you are cleared to launch. Good hunting.'],
  'r.s1.feetWet': ['HAWKEYE', 'Hawk, bandits inbound from the north, angels low. Weapons free.'],
  'r.s1.tallyho': ['HAWK', 'Tally ho! Multiple bandits, twelve o\'clock!'],
  'r.s1.six': ['HAWKEYE', 'Watch your six, Hawk! Bandits closing from behind!'],
  'r.s1.ships': ['HAWKEYE', 'Surface group ahead. Expect SAMs — stay low, stay fast.'],
  'r.s1.eo': ['HAWKEYE', 'Priority target! Heavy bomber heading for the fleet. Take it down!'],
  'r.s1.eoDown': ['BOSS', 'Bomber splashed! Outstanding work, Hawk.'],
  'r.s1.tanker': ['TEXACO', 'Hawk, Texaco on station. Come get a drink.'],
  'r.s2.brief': ['BOSS', 'Canyon run. Stay under the radar ceiling or their SAMs will light you up.'],
  'r.s2.ceiling': ['HAWKEYE', 'You\'re above the ceiling! Get down, Hawk!'],
  'r.s2.xb70': ['HAWKEYE', 'XB-70 spotted running the canyon — don\'t let it escape!'],
  'r.s2.popup': ['HAWK', 'Target in sight. Pulling up!'],
  'r.s2.hit': ['BOSS', 'Direct hit! Now get out of there!'],
  'r.s2.sams': ['HAWKEYE', 'SAMs in the air! Break, break!'],
  'r.s3.brief': ['BOSS', 'This is it. Enemy strike package over the clouds. Stop them.'],
  'r.s3.ace': ['HAWKEYE', 'Fifth-gen bandit — he\'s good. Stay on him!'],
  'r.s3.fortress': ['HAWKEYE', 'There\'s the big one. Target the engines!'],
  'r.s3.win': ['BOSS', 'Mission accomplished. Bring it home, Hawk.'],
  'r.gen.goodKill': ['WINGMAN', 'Good kill! Good kill!'],
  'r.gen.fox2': ['HAWK', 'Fox two!'],
  'r.gen.missile': ['WINGMAN', 'Missile launch! Break right!'],
  'r.gen.climax': ['HAWK', 'Engaging!'],
  'r.gen.hit': ['HAWK', 'I\'m hit!'],
  'r.gen.down': ['BOSS', 'Hawk is down! ...Hawk, respond!']
};
