export default {
  'ui.pressStart': 'PRESS START',
  'ui.tapToStart': 'TAP TO START',
  'ui.getReady': 'GET READY',
  'ui.stage': 'STAGE',
  'ui.missionComplete': 'MISSION COMPLETE',
  'ui.continue': 'CONTINUE?',
  'ui.gameOver': 'GAME OVER',
  'ui.eo': 'EMERGENCY ORDER',
  'ui.eoClear': 'ORDER CLEARED',
  'ui.eoFail': 'ORDER FAILED',
  'ui.climaxReady': 'CLIMAX READY',
  'ui.shotDown': 'SHOT DOWN',
  'ui.lock': 'LOCK',
  // radio: [callsign, line]
  'r.s1.launch': ['BOSS', 'Hawk, you are cleared to launch. Good hunting.'],
  'r.s1.feetWet': ['HAWKEYE', 'Hawk, bandits inbound from the north, angels low. Weapons free.'],
  'r.s1.tallyho': ['HAWK', 'Tally ho! Multiple bandits, twelve o\'clock!'],
  'r.s1.six': ['HAWKEYE', 'Watch your six, Hawk! Bandits closing from behind!'],
  'r.s1.ships': ['HAWKEYE', 'Surface group ahead. Expect SAMs — stay low, stay fast.'],
  'r.s1.eo': ['HAWKEYE', 'Priority target! Heavy bomber heading for the fleet. Take it down!'],
  'r.s1.eoDown': ['BOSS', 'Bomber splashed! Outstanding work, Hawk.'],
  'r.s1.tanker': ['TEXACO', 'Hawk, Texaco on station. Come get a drink.'],
  'r.s2.brief': ['BOSS', 'Canyon run. Stay under the radar ceiling or their SAMs will light you up.'],
  'r.s2.ceiling': ['HAWKEYE', 'You\'re above the ceiling! Get down, Hawk!'],
  'r.s2.xb70': ['HAWKEYE', 'XB-70 spotted running the canyon — don\'t let it escape!'],
  'r.s2.popup': ['HAWK', 'Target in sight. Pulling up!'],
  'r.s2.hit': ['BOSS', 'Direct hit! Now get out of there!'],
  'r.s2.sams': ['HAWKEYE', 'SAMs in the air! Break, break!'],
  'r.s3.brief': ['BOSS', 'This is it. Enemy strike package over the clouds. Stop them.'],
  'r.s3.ace': ['HAWKEYE', 'Fifth-gen bandit — he\'s good. Stay on him!'],
  'r.s3.fortress': ['HAWKEYE', 'There\'s the big one. Target the engines!'],
  'r.s3.win': ['BOSS', 'Mission accomplished. Bring it home, Hawk.'],
  'r.gen.goodKill': ['WINGMAN', 'Good kill! Good kill!'],
  'r.gen.fox2': ['HAWK', 'Fox two!'],
  'r.gen.missile': ['WINGMAN', 'Missile launch! Break right!'],
  'r.gen.climax': ['HAWK', 'Engaging!'],
  'r.gen.hit': ['HAWK', 'I\'m hit!'],
  'r.gen.down': ['BOSS', 'Hawk is down! ...Hawk, respond!'],
  'opt.title': 'OPTIONS',
  'opt.quality': 'GRAPHICS QUALITY',
  'opt.qualityHint': 'AUTO picks a preset for your GPU; dynamic resolution keeps the frame rate steady.',
  'opt.fps': 'FRAME RATE CAP',
  'opt.uncapped': 'UNCAPPED',
  'opt.difficulty': 'DIFFICULTY',
  'opt.assist': 'AIM ASSIST',
  'opt.assistHint': 'Magnetic reticle, larger lock circle and bullet steering toward targets.',
  'opt.autoFire': 'AUTO VULCAN',
  'opt.missileMode': 'MISSILE BUTTON',
  'opt.tap': 'TAP = 1 MISSILE',
  'opt.paint': 'HOLD & RELEASE',
  'opt.invertY': 'INVERT Y (ARCADE)',
  'opt.mouse': 'MOUSE FLIGHT',
  'opt.tilt': 'TILT CONTROLS',
  'opt.master': 'MASTER VOLUME',
  'opt.music': 'MUSIC',
  'opt.sfx': 'SOUND EFFECTS',
  'opt.lang': 'LANGUAGE',
  'opt.shake': 'CAMERA SHAKE',
  'opt.flashing': 'REDUCED FLASHING',
  'opt.colorblind': 'COLOUR-BLIND LOCK MARKERS',
  'opt.back': 'BACK',
  'menu.start': 'START MISSION',
  'menu.options': 'OPTIONS',
  'menu.howto': 'HOW TO PLAY',
  'menu.credits': 'CREDITS',
  'menu.resume': 'RESUME',
  'menu.restart': 'RESTART STAGE',
  'menu.quit': 'QUIT TO TITLE',
  'menu.paused': 'PAUSED',
  'menu.continue': 'CONTINUE',
  'hangar.title': 'SELECT AIRCRAFT',
  'hangar.scheme': 'PAINT SCHEME',
  'hangar.go': 'PRESS START TO SORTIE',
  'scheme.standard': 'STANDARD',
  'scheme.camo': 'CAMOUFLAGE',
  'scheme.special': 'SPECIAL',
  'scheme.lowvis': 'LOW VISIBILITY',
  'brief.mission': 'MISSION',
  'brief.go': 'PRESS START',
  'brief.s1': 'Launch from the carrier at dawn and intercept the enemy strike group over the ocean. A heavy bomber is heading for the fleet — expect an Emergency Order.',
  'brief.s2': 'Run the canyon under the radar ceiling — fly high and the SAM sites will light you up. Destroy the XB-70 if it appears, then pop up and hit the fortified target before time runs out.',
  'brief.s3': 'Above the clouds at sunset, the enemy commits everything: stealth fighters, their best ace and a strategic bomber. Take out its four engines, then bring it home to the boat.',
  'res.clear': 'STAGE CLEAR',
  'res.kills': 'ENEMIES DOWN',
  'res.combo': 'BEST COMBO',
  'res.time': 'TIME',
  'res.down': 'DOWN RATE',
  'res.rank': 'RANK',
  'res.eo': 'EMERGENCY ORDER',
  'res.score': 'STAGE SCORE',
  'res.total': 'TOTAL SCORE',
  'res.cleared': 'CLEARED',
  'res.failed': 'FAILED',
  'end.title': 'MISSION ACCOMPLISHED',
  'end.sub': 'THE LINE HELD. WELCOME HOME, HAWK.',
  'end.final': 'FINAL SCORE',
  'end.thanks': 'THANK YOU FOR PLAYING',
  'howto.title': 'HOW TO PLAY',
  'howto.kb': 'KEYBOARD: WASD/ARROWS fly · J/SPACE missile · K Climax · SHIFT fast · CTRL slow · Q/E or double-tap roll · F flares · ESC pause',
  'howto.pad': 'GAMEPAD: left stick fly · A missile · B/X Climax · RT fast · LT slow · LB/RB roll · Y flares · START pause',
  'howto.touch': 'TOUCH: drag anywhere on the left to fly · MISSILE / CLIMAX / FLARE buttons · slider for speed · flick to roll',
  'howto.tips': 'Sweep the reticle over enemies to lock, then fire. Fill the CLIMAX gauge and unleash it to slow time and lock everything. Roll or drop flares when you hear the missile alarm.'
};
