// Stage strings (Thai). Missing keys fall back to English.
import { radioStrings } from './stages_en.js';

export default {
  ...radioStrings('th'),

  'stage.ocean.name': 'ขอบฟ้าสีคราม',
  'stage.ocean.sub': 'ออกปฏิบัติการ',
  'brief.ocean': 'ดีดตัวขึ้นจากเรือบรรทุกเครื่องบิน แล้วกวาดล้างเครื่องบินข้าศึกเหนือทะเลเปิด',
  'stage.emerald.name': 'ยอดเขามรกต',
  'stage.emerald.sub': 'ที่ราบสูง',
  'brief.emerald': 'บินเลาะหุบเขาเขียวขจีใต้ยอดเขาหิมะ หยุดเฮลิคอปเตอร์ขนทหารก่อนที่มันจะข้ามช่องเขา',
  'eo.emerald': 'ยิงเฮลิคอปเตอร์ลำเลียงให้ตก 8 ลำ',
  'stage.canyon.name': 'หุบผาแดง',
  'stage.canyon.sub': 'ช่องทางมรณะ',
  'brief.canyon': 'ร้อยผ่านหุบผาแดง ลอดซุ้มหิน หลบเสาหิน ทางออกจะแยกเป็นสองเส้นทาง',
  'eo.canyon': 'ทำลายเครื่องบินทิ้งระเบิดในหุบเขา',
  'stage.sunset.name': 'กองเรืออัสดง',
  'stage.sunset.sub': 'ศึกกองเรือ',
  'brief.sunset': 'ทลายกองเรือข้าศึกยามตะวันตกดินและหยุดเครื่องบินทิ้งระเบิดหนัก เครื่องบินเติมน้ำมันรออยู่ปลายทาง',
  'eo.sunset': 'ยิงเครื่องบินทิ้งระเบิดหนักให้ตก',
  'stage.glacier.name': 'ฟยอร์ดธารน้ำแข็ง',
  'stage.glacier.sub': 'เหล็กกล้าเยือกแข็ง',
  'brief.glacier': 'บินต่ำเลาะฟยอร์ดน้ำแข็ง หลบแท่งน้ำแข็ง และทำลายฐานปืนต่อสู้อากาศยานริมฝั่ง',
  'eo.glacier': 'ทำลายฐานต่อสู้อากาศยาน 6 แห่ง',
  'stage.dunes.name': 'เนินทรายทองคำ',
  'stage.dunes.sub': 'ไล่ล่ากลางพายุทราย',
  'brief.dunes': 'ข้าศึกจะไล่ล่าคุณข้ามทะเลทราย ใช้ปืนยิงขีปนาวุธร่อน เพราะล็อกเป้าไม่ได้',
  'eo.dunes': 'ยิงขีปนาวุธร่อน 3 ลูก — ใช้ปืนเท่านั้น',
  'stage.clouds.name': 'ทะเลเมฆ',
  'stage.clouds.sub': 'ดวลเอซ',
  'brief.clouds': 'เหนือทะเลเมฆยามพลบค่ำ นักบินฝีมือดีที่สุดของข้าศึกรอคุณอยู่',
  'eo.clouds': 'เอาชนะเอซข้าศึก',
  'stage.strike.name': 'จู่โจมหุบเขา',
  'stage.strike.sub': 'ลอดใต้เรดาร์',
  'brief.strike': 'บินใต้เพดานเรดาร์และแข่งกับเวลา จากนั้นไต่ขึ้นแล้วทำลายเป้าหมาย',
  'eo.strike': 'ทำลายเป้าหมาย',
  'stage.fortress.name': 'ป้อมปราการลอยฟ้า',
  'stage.fortress.sub': 'แนวรบสุดท้าย',
  'brief.fortress': 'ป้อมบินลอยฟ้า ทำลายเครื่องยนต์ทั้งสี่ แล้วนำเครื่องกลับลงจอดบนเรือ',
  'eo.fortress': 'ทำลายป้อมบินลอยฟ้า',
  'stage.aurora.name': 'แสงออโรรา',
  'stage.aurora.sub': 'ภารกิจลับ',
  'brief.aurora': 'ท้องฟ้าลับใต้แสงออโรรา ข้าศึกจะไม่ยิงตอบ ยิงให้ตกทั้งหมด',

  'stage.storm.name': 'ธันเดอร์เฮด',
  'stage.storm.sub': 'แนวพายุ',
  'brief.storm': 'บินต่ำใต้กำแพงพายุ เครื่องทิ้งระเบิดหนักซ่อนตัวอยู่ในเมฆ',
  'eo.storm': 'ยิงเครื่องทิ้งระเบิดในพายุให้ตก',
  'stage.volcano.name': 'สันเขาเถ้าถ่าน',
  'stage.volcano.sub': 'ภูเขาไฟ',
  'brief.volcano': 'หินดำและเถ้าสีแดง ทำลายฐานปืนต่อสู้อากาศยานบนไหล่เขา',
  'eo.volcano': 'ทำลายฐานต่อสู้อากาศยาน 6 แห่ง',
  'stage.nightfleet.name': 'กองเรือเที่ยงคืน',
  'stage.nightfleet.sub': 'จู่โจมยามวิกาล',
  'brief.nightfleet': 'กองเรือข้าศึกดับไฟแล่นในคืนนี้ จมเรือพิฆาตคุ้มกันให้หมด',
  'eo.nightfleet': 'จมเรือพิฆาตคุ้มกัน 3 ลำ',
  'stage.whiteout.name': 'ไวต์เอาต์',
  'stage.whiteout.sub': 'ทุ่งหิมะ',
  'brief.whiteout': 'หุบเขาสีขาวในหมอกสีขาว ยิงขีปนาวุธร่อนที่บินเรี่ยหิมะให้ร่วง',
  'eo.whiteout': 'ยิงขีปนาวุธร่อน 4 ลูก — ใช้ปืนเท่านั้น',
  'stage.ravine.name': 'หุบผาสนธยา',
  'stage.ravine.sub': 'คมมีด',
  'brief.ravine': 'หุบผาที่แคบที่สุดในแผนที่ บินใต้เรดาร์แล้วไล่ล่าเครื่องทิ้งระเบิด',
  'eo.ravine': 'ทำลายเครื่องทิ้งระเบิดในหุบผา',
  'stage.jetstream.name': 'เจ็ตสตรีม',
  'stage.jetstream.sub': 'เพดานบินสูง',
  'brief.jetstream': 'รุ่งอรุณเหนือทะเลเมฆ นักบินเอซของข้าศึกสองลำบินมาด้วยกัน',
  'eo.jetstream': 'เอาชนะคู่นักบินเอซ',
  'stage.badlands.name': 'แดนร้างใต้แสงจันทร์',
  'stage.badlands.sub': 'ข้ามทะเลทรายยามค่ำ',
  'brief.badlands': 'เนินทรายสีเงินใต้แสงจันทร์ หยุดการลำเลียงทางอากาศยามค่ำก่อนถึงป้อมบิน',
  'eo.badlands': 'ยิงเฮลิคอปเตอร์ลำเลียงให้ตก 8 ลำ',
  'stage.stratos.name': 'สตราโตสเฟียร์',
  'stage.stratos.sub': 'ขอบอวกาศ',
  'brief.stratos': 'สุดขอบฟ้า ข้าศึกจะไม่ยิงตอบ ยิงให้ตกทั้งหมด',

  'flow.pleaseWait': 'โปรดรอสักครู่',
  'flow.route': 'เส้นทาง',
  'flow.stage': 'ด่าน',
  'flow.paintOf': 'ลายพ่นสี{scheme}',
  'flow.ready': 'กด START',
  'flow.bonus': 'เปิดเส้นทางลับแล้ว',
  'flow.bonusLocked': 'เส้นทางลับยังไม่เปิด — ผ่านภารกิจฉุกเฉิน {n}/{need}',
  'flow.next': 'ถัดไป',
  'status.title': 'รายงานสถานะ',
  'status.midgame': 'ผลกลางเกม',
  'status.score': 'คะแนน',
  'status.downed': 'ยิงตกรวม',
  'status.combo': 'คอมโบสูงสุด',
  'status.time': 'เวลาเล่น',
  'status.grade': 'เกรด'
};
